apps/core/urls.py
from django.urls import path
from django.shortcuts import redirect
from .views import home_view, dashboard_view

app_name = 'core'

urlpatterns = [
    path('', lambda request: redirect('home/')),
    path('home/', home_view, name='home'),
    path('dashboard/', dashboard_view, name='dashboard'),
]

apps/user/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    # path('auth/login/', auth_views.LoginView.as_view(template_name='pages/user/login.html'), name='login'),
    # path('auth/logout/', auth_views.LogoutView.as_view(template_name='pages/user/logout.html'), name='logout'),
    path('auth/login/', LoginView.as_view(), name='login'),
    path('auth/logout/', LogoutView.as_view(), name='logout'),
    path('auth/register/', RegisterView.as_view(), name='register'),

    path('account/activate/<uidb64>/<token>/', ActivateAccountView.as_view(), name='activate'),
    path('account/activate/done/', RegisterDoneView.as_view(), name='register_done'),
    path('account/profile/', AccountProfileView.as_view(), name='profile'),
    path('account/password/change/', PasswordChangeView.as_view(), name='password_change'),
    path('account/update/', AccountUpdateView.as_view(), name='update'),

    path('password/reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password/reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password/reset/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password/reset/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('user/', include('apps.user.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from utils.hashed_filename_generator import generate_hashed_filename
from uuid import uuid4
import os

# Create your models here.
class User(AbstractUser):
    class Meta:
        db_table = 'auth_user'
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'
        ordering = ['username']
        indexes = [
            models.Index(fields=['username']),
            models.Index(fields=['email']),
        ]
        constraints = [
            models.UniqueConstraint(fields=['username'], name='unique_username'),
            models.UniqueConstraint(fields=['email'], name='unique_email'),
        ]

    def get_path_to_profile_picture(instance, filename):
        return generate_hashed_filename(instance, 'users/profile_pictures', filename)
    
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False, verbose_name='ID')
    email = models.EmailField(max_length=255, unique=True, verbose_name='E-mail')
    profile_picture = models.ImageField(upload_to=get_path_to_profile_picture, blank=True, null=True, verbose_name='Foto de perfil')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Atualizado em')
    
    def save(self, *args, **kwargs):
        if self.pk:
            try:
                old_instance = User.objects.get(pk=self.pk)

                if old_instance.profile_picture and self.profile_picture != old_instance.profile_picture:
                    if os.path.isfile(old_instance.profile_picture.path):
                        os.remove(old_instance.profile_picture.path)
            except User.DoesNotExist:
                pass
            
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        if self.profile_picture:
            if os.path.isfile(self.profile_picture.path):
                os.remove(self.profile_picture.path)
        
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.get_full_name() or self.username

apps/user/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

# Create your forms here.
User = get_user_model()

class UserLoginForm(AuthenticationForm):
    pass

class UserRegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class UserUpdateForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'profile_picture')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        if 'password' in self.fields:
            self.fields.pop('password')

apps/user/views.py
from django.conf import settings
# from django.contrib import messages
from django.contrib.auth import get_user_model, views as auth_views
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.views import View
from django.views.generic import CreateView, UpdateView, TemplateView
from .forms import UserRegisterForm, UserUpdateForm
from .tokens import account_activation_token

# Create your views here.
User = get_user_model()

def redirect_authenticated_user(request, redirect_url=None):
    if request.user.is_authenticated:
        return redirect(redirect_url or settings.LOGIN_REDIRECT_URL)
    
    return None

class LoginView(auth_views.LoginView):
    template_name = 'pages/user/login.html'
    redirect_authenticated_user = True

class LogoutView(auth_views.LogoutView, LoginRequiredMixin):
    template_name = 'pages/user/logout.html'

class RegisterView(CreateView):
    template_name = 'pages/user/register.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('user:register_done')
    
    def dispatch(self, request, *args, **kwargs):
        response = redirect_authenticated_user(request, 'core:home')

        return response if response else super().dispatch(request, *args, **kwargs)
    
    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        
        user.save()

        uidb64 = urlsafe_base64_encode(force_bytes(user.pk))
        token = account_activation_token.make_token(user)

        self.send_activation_email(user, uidb64, token)

        return super().form_valid(form)

    def send_activation_email(self, user, uidb64, token):
        current_site = get_current_site(self.request)
        mail_subject = 'Ative sua conta'
        message = render_to_string('emails/activation_email.html', {
            'user': user,
            'domain': current_site.domain,
            'protocol': 'https' if self.request.is_secure() else 'http',
            'uidb64': uidb64,
            'token': token,
        })
        email = EmailMessage(mail_subject, message, to=[user.email])

        email.send()
    
class ActivateAccountView(View):
    def get(self, request, uidb64, token):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True

            user.save()

            return render(request, 'pages/user/activation_success.html')
        else:
            return render(request, 'pages/user/activation_invalid.html')
        
class RegisterDoneView(TemplateView):
    template_name = 'pages/user/register_done.html'
    
    def dispatch(self, request, *args, **kwargs):
        response = redirect_authenticated_user(request, 'core:home')

        return response if response else super().dispatch(request, *args, **kwargs)
    
class PasswordResetView(auth_views.PasswordResetView):
    template_name = 'pages/user/password_reset.html'
    email_template_name = 'emails/password_reset_email.html'
    subject_template_name = 'emails/password_reset_subject.txt'
    success_url = reverse_lazy('user:password_reset_done')
    form_class = PasswordResetForm
    
    def dispatch(self, request, *args, **kwargs):
        response = redirect_authenticated_user(request, 'core:home')

        return response if response else super().dispatch(request, *args, **kwargs)

class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'pages/user/password_reset_done.html'
    
    def dispatch(self, request, *args, **kwargs):
        response = redirect_authenticated_user(request, 'core:home')

        return response if response else super().dispatch(request, *args, **kwargs)

class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = 'pages/user/password_reset_confirm.html'
    success_url = reverse_lazy('user:password_reset_complete')
    
    def dispatch(self, request, *args, **kwargs):
        response = redirect_authenticated_user(request, 'core:home')

        return response if response else super().dispatch(request, *args, **kwargs)

class PasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'pages/user/password_reset_complete.html'

    def dispatch(self, request, *args, **kwargs):
        response = redirect_authenticated_user(request, 'core:home')

        return response if response else super().dispatch(request, *args, **kwargs)

class AccountProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'pages/user/account_profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = UserUpdateForm(instance=self.request.user)

        return context

class AccountUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'pages/user/account_profile.html'
    model = User
    form_class = UserUpdateForm
    success_url = reverse_lazy('user:profile')

    def get_object(self, queryset=None):
        return self.request.user

class PasswordChangeView(LoginRequiredMixin, auth_views.PasswordChangeView):
    template_name = 'pages/user/password_change.html'
    success_url = reverse_lazy('user:profile')

class AccountSecurityView(LoginRequiredMixin, TemplateView):
    template_name = 'pages/user/account_security.html'

templates/pages/user/account_profile.html
{% extends 'base/base.html' %}

{% load static %}
{% load humanize %}
{% load crispy_forms_tags %}

{% block title %}SME Cabo Verde | Minha Conta{% endblock title %}

{% block content %}
<div class="container pt-3">
    <!-- <div class="row">
        <div class="col">
            <nav aria-label="breadcrumb" class="bg-body-tertiary rounded-3 p-3 mb-4">
                <ol class="breadcrumb mb-0">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">User</a></li>
                    <li class="breadcrumb-item active" aria-current="page">User Profile</li>
                </ol>
            </nav>
        </div>
    </div> -->

    <div class="row">
        <div class="col-lg-4">
            <div class="card mb-4">
                <!-- <div class="card-header">
                    <h4 class="mb-0 text-center">Foto de perfil</h4>
                </div> -->
                <div class="card-body text-center">
                    {% if user.profile_picture %}
                    <img src="{{ user.profile_picture.url }}" alt="Foto de perfil" class="rounded-circle img-fluid"
                        style="width: 150px;">
                    {% else %}
                    <img src="{% static 'img/default-profile-image.jpg' %}" alt="Foto de perfil padrão"
                        class="rounded-circle img-fluid" style="width: 150px;">
                    {% endif %}
                    <h5 class="my-3">
                        {{ user.get_full_name|default:"Nome não informado" }}
                    </h5>
                    <p class="text-muted mb-0">
                        {{ user.email |default:"Email não informado" }}
                    </p>
                    <p class="text-muted mb-0">
                        Usuário desde: {{ user.date_joined|date:"d/m/Y" }}
                    </p>
                    <div class="d-flex flex-column flex-sm-row justify-content-center m-3 gap-2">
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                            data-bs-target="#staticBackdrop">Alterar dados</button>
                        <a href="{% url 'user:password_change' %}" class="btn btn-outline-primary">Alterar senha</a>
                    </div>
                </div>
            </div>
            <!-- <div class="card mb-4 mb-lg-0">
                <div class="card-body">
                    
                </div>
            </div> -->
        </div>
        <div class="col-lg-8">
            <div class="card mb-4">
                <div class="card-header">
                    <h4 class="mb-0">Informações da conta</h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-4">
                            <strong>Nome</strong>
                        </div>
                        <div class="col-sm-8">
                            <p class="text-muted mb-0">{{ user.first_name|default:"Não informado" }}</p>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-4">
                            <strong>Sobrenome</strong>
                        </div>
                        <div class="col-sm-8">
                            <p class="text-muted mb-0">{{ user.last_name|default:"Não informado" }}</p>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-4">
                            <strong>Usuário</strong>
                        </div>
                        <div class="col-sm-8">
                            <p class="text-muted mb-0">{{ user.username|default:"Não informado" }}</p>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-4">
                            <strong>E-mail</strong>
                        </div>
                        <div class="col-sm-8">
                            <p class="text-muted mb-0">{{ user.email|default:"Não informado" }}</p>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-4">
                            <strong>Status</strong>
                        </div>
                        <div class="col-sm-8">
                            <p class="text-muted mb-0">
                                {% if user.is_active %}
                                <span class="badge bg-success">Ativo</span>
                                {% else %}
                                <span class="badge bg-danger">Inativo</span>
                                {% endif %}
                            </p>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-4">
                            <strong>Membro da equipe</strong>
                        </div>
                        <div class="col-sm-8">
                            <p class="text-muted mb-0">
                                {% if user.is_staff %}
                                <span class="badge bg-success">Sim</span>
                                {% else %}
                                <span class="badge bg-danger">Não</span>
                                {% endif %}
                            </p>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-4">
                            <strong>Superusuário</strong>
                        </div>
                        <div class="col-sm-8">
                            <p class="text-muted mb-0">
                                {% if user.is_superuser %}
                                <span class="badge bg-success">Sim</span>
                                {% else %}
                                <span class="badge bg-danger">Não</span>
                                {% endif %}
                            </p>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-4">
                            <strong>Atualizado em</strong>
                        </div>
                        <p class="text-muted mb-0">
                            {{ user.updated_at|date:"d/m/Y à\s H:i" }}
                            <span class="d-block d-sm-inline">({{ user.updated_at|naturaltime }})</span>
                        </p>
                    </div>
                </div>
            </div>
            <!-- <div class="row">
                <div class="col-md-6">
                    <div class="card mb-4 mb-md-0">
                        <div class="card-body">
                            
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card mb-4 mb-md-0">
                        <div class="card-body">
                            
                        </div>
                    </div>
                </div>
            </div> -->
        </div>

        <!-- Modal -->
        <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
            aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <form action="{% url 'user:update' %}" method="post" enctype="multipart/form-data"
                        class="needs-validation" id="modalForm" novalidate>
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="staticBackdropLabel">Atualizar dados da conta</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            {% csrf_token %}

                            {{ form|crispy }}
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                            <button type="submit" class="btn btn-primary">Salvar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block js %}
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const modalElement = document.getElementById('staticBackdrop');
        const formElement = modalElement.querySelector('form');

        {% if form.errors %}
        const modal = new bootstrap.Modal(modalElement, {
            backdrop: 'static',
            keyboard: false
        });

        modal.show();

        modalElement.addEventListener('hidden.bs.modal', function () {
            // Remove mensagens e classes de erro
            modalElement.querySelectorAll('.invalid-feedback').forEach(el => el.remove());
            modalElement.querySelectorAll('.is-invalid').forEach(el => el.classList.remove('is-invalid'));

            // Reseta os valores dos campos para o estado inicial
            formElement.reset();
        });
        {% endif %}
    });
</script>
{% endblock js %}

templates/pages/user/activation_invalid.html
{% extends 'base/base-auth.html' %}

{% load crispy_forms_tags %}

{% block title %}SME Cabo Verde | Erro na ativação{% endblock title %}

{% block content %}
<h2>Erro na ativação!</h2>
<p>O link de ativação é inválido ou já foi utilizado. Por favor, verifique o seu e-mail para obter o link correto ou entre em contato com o suporte.</p>
<p>Se você não recebeu o e-mail de ativação, verifique sua caixa de spam ou lixo eletrônico.</p>
<p>Se você ainda não recebeu o e-mail, clique no botão abaixo para reenviar o e-mail de ativação.</p>
<a href="#" class="btn btn-primary w-100">Reenviar e-mail de ativação</a>
<a href="{% url 'user:login' %}" class="btn btn-secondary w-100 mt-2">Voltar para o login</a>
{% endblock content %}

templates/pages/user/activation_success.html
{% extends 'base/base-auth.html' %}

{% load crispy_forms_tags %}

{% block title %}SME Cabo Verde | Conta ativada com sucesso{% endblock title %}

{% block content %}
<h2>Conta ativada com sucesso!</h2>
<p>Você pode fazer login agora.</p>
<a href="{% url 'user:login' %}" class="btn btn-primary w-100">Fazer login</a>
{% endblock content %}

templates/pages/user/login.html
{% extends 'base/base-auth.html' %}

{% load crispy_forms_tags %}

{% block title %}SME Cabo Verde | Entrar{% endblock title %}

{% block css %}
<style>
    #div_id_password {
        margin-bottom: 0 !important;
    }
</style>
{% endblock css %}

{% block content %}
<!-- Alert messages -->
{% if messages %}
{% include 'partials/_alert-message.html' %}
{% endif %}

<!-- Title -->
<h1 class="h3 mb-3 fw-normal">{{ title }}</h1>

<!-- Form -->
<form action="" method="post" class="needs-validation" novalidate>
    <!-- CSRF Token -->
    {% csrf_token %}

    {{ form|crispy }}

    <p class="mt-2">Esqueceu a senha?
        <a href="{% url 'user:password_reset' %}">Clique aqui</a>
    </p>

    <button type="submit" class="btn btn-primary w-100">Entrar</button>
</form>

<!-- Links -->
<div class="mt-3 d-flex justify-content-center">
    <p>Não tem uma conta?
        <a href="{% url 'user:register' %}">Registre-se</a>
    </p>
</div>
{% endblock content %}

templates/pages/user/logout.html
{% extends 'base/base-auth.html' %}

{% block title %}SME Cabo Verde | Sessão encerrada{% endblock title %}

{% block content %}
<h2>Você foi desconectado!</h2>
<p class="mt-3">Você foi desconectado com sucesso. Se você não fez isso, entre em contato com o suporte.</p>
<a href="{% url 'user:login' %}" class="btn btn-primary w-100">Entrar novamente</a>
<a href="{% url 'core:home' %}" class="btn btn-secondary w-100 mt-2">Voltar para a página inicial</a>
{% endblock content %}

templates/pages/user/password_change.html
{% extends 'base/base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}SME Cabo Verde | Alterar Senha{% endblock title %}

{% block css %}
<style>
    .asteriskField {
        color: red;
    }
</style>
{% endblock css %}

{% block content %}
<div class="container pt-3">
    <h2>Alterar senha</h2>
    <p>Digite sua senha atual e a nova senha desejada.</p>
    <form action="" method="post">
        {% csrf_token %}

        {{ form|crispy }}

        <button type="submit" class="btn btn-primary w-100">Alterar senha</button>
    </form>
    <div class="mt-3">
        <a href="{% url 'user:profile' %}" class="btn btn-secondary w-100">Voltar para o perfil</a>
    </div>
</div>
{% endblock content %}

templates/pages/user/password_reset.html
{% extends 'base/base-auth.html' %}

{% load crispy_forms_tags %}

{% block title %}SME Cabo Verde | Redefinir senha{% endblock title %}

{% block content %}
<h2>Redefinição de Senha</h2>
<p>Digite seu e-mail para receber um link de redefinição de senha.</p>
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary w-100">Enviar</button>
</form>
{% endblock content %}

templates/pages/user/password_reset_complete.html
{% extends 'base/base-auth.html' %}

{% load crispy_forms_tags %}

{% block title %}SME Cabo Verde | Redefinir senha{% endblock title %}

{% block content %}
<h2>Senha redefinida com sucesso!</h2>
<p>Agora você pode <a href="{% url 'user:login' %}">fazer login</a> com sua nova senha. Se você não fez isso, entre em
	contato com o suporte.</p>
<a href="{% url 'core:home' %}" class="btn btn-primary w-100">Voltar para o início</a>
{% endblock content %}

templates/pages/user/password_reset_confirm.html
{% extends 'base/base-auth.html' %}

{% load crispy_forms_tags %}

{% block title %}SME Cabo Verde | Redefinir senha{% endblock title %}

{% block content %}
<h2>Redefinir senha</h2>

{% if validlink %}
<form method="post">
	{% csrf_token %}

	{{ form|crispy }}
	<button type="submit" class="btn btn-success w-100">Alterar senha</button>
</form>
{% else %}
<div class="alert alert-danger">
	O link de redefinição de senha é inválido ou expirou.
</div>
{% endif %}
{% endblock content %}

templates/pages/user/password_reset_done.html
{% extends 'base/base-auth.html' %}

{% load crispy_forms_tags %}

{% block title %}SME Cabo Verde | Redefinir senha{% endblock title %}

{% block content %}
<h2>Email enviado!</h2>
<p>Se o email informado estiver cadastrado, você receberá as instruções para redefinir sua senha.</p>
<a href="{% url 'user:login' %}" class="btn btn-primary w-100">Fazer login</a>
<p class="mt-2">Não recebeu o email? Verifique sua caixa de spam ou tente novamente.</p>
{% endblock content %}

templates/pages/user/register.html
{% extends 'base/base-auth.html' %}

{% load crispy_forms_tags %}

{% block title %}SME Cabo Verde | Criar conta{% endblock title %}

{% block content %}
<!-- Alert messages -->
{% if messages %}
    {% include 'partials/_alert-message.html' %}
{% endif %}

<!-- Title -->
<h1 class="h3 mb-3 fw-normal">{{ title }}</h1>

<!-- Form -->
<form action="" method="post" class="needs-validation" novalidate>
    <!-- CSRF Token -->
    {% csrf_token %}

    {{ form|crispy }}

    <button type="submit" class="btn btn-primary w-100">Criar conta</button>
</form>

<!-- Links -->
<div class="mt-3 d-flex justify-content-center">
    <p>Já tem uma conta?
        <a href="{% url 'user:login' %}">Entre aqui</a>
    </p>
</div>
{% endblock content %}

templates/pages/user/register_done.html
{% extends 'base/base-auth.html' %}

{% load crispy_forms_tags %}

{% block title %}SME Cabo Verde | Conta cadastrada{% endblock title %}

{% block content %}
<h2>Conta cadastrada com sucesso!</h2>
<p>Verifique seu email para ativar sua conta. Se você não recebeu o email, entre em contato com o suporte.</p>
<a href="{% url 'user:login' %}" class="btn btn-primary w-100">Fazer login</a>
{% endblock content %}